#!/usr/bin/bash

WINDOWS_WINPEASANY_URL="https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEASany.exe"
WINDOWS_NC_LOCAL="/usr/share/windows-resources/binaries/nc.exe"
WINDOWS_ACCESSCHK_OLD_URL="https://web.archive.org/web/20071007120748if_/http://download.sysinternals.com/Files/Accesschk.zip%0D"
WINDOWS_PROCDUMP_URL="https://download.sysinternals.com/files/Procdump.zip"
WINDOWS_PSEXEC_URL="https://download.sysinternals.com/files/PSTools.zip"
WINDOWS_JUICYPOTATO64_URL="https://github.com/ohpe/juicy-potato/releases/latest/download/JuicyPotato.exe"
WINDOWS_JUICYPOTATO32_URL="https://github.com/ivanitlearning/Juicy-Potato-x86/releases/latest/download/Juicy.Potato.x86.exe"
WINDOWS_PRINTSPOOFER64_URL="https://github.com/itm4n/PrintSpoofer/releases/latest/download/PrintSpoofer64.exe"
WINDOWS_PRINTSPOOFER32_URL="https://github.com/itm4n/PrintSpoofer/releases/latest/download/PrintSpoofer32.exe"
WINDOWS_MIMIKATZ_URL="https://github.com/gentilkiwi/mimikatz/releases/latest/download/mimikatz_trunk.zip"
WINDOWS_MIMIKATZ_OLD_URL="https://github.com/caday00/mimikatz2.1.1/raw/master/mimikatz_trunk.zip"

WINDOWS_MS16_032_64_URL="https://github.com/SecWiki/windows-kernel-exploits/raw/master/MS16-032/x64/ms16-032.exe"
WINDOWS_MS16_032_32_URL="https://github.com/SecWiki/windows-kernel-exploits/raw/master/MS16-032/x86/ms16-032.exe"
WINDOWS_NMAP32_URL="https://github.com/andrew-d/static-binaries/raw/master/binaries/windows/x86/nmap.exe"
WINDOWS_EXPLOIT_SUGGESTER_URL="https://raw.githubusercontent.com/AonCyberLabs/Windows-Exploit-Suggester/master/windows-exploit-suggester.py"
WINDOWS_POWERVIEW_URL="https://raw.githubusercontent.com/PowerShellEmpire/PowerTools/master/PowerView/powerview.ps1"
WINDOWS_GETSPN_URL="https://raw.githubusercontent.com/EmpireProject/Empire/master/data/module_source/situational_awareness/network/Get-SPN.ps1"
WINDOWS_KERBEROAST_URL="https://github.com/nidem/kerberoast"
WINDOWS_INVOKE_KERBEROAST_URL="https://raw.githubusercontent.com/EmpireProject/Empire/master/data/module_source/credentials/Invoke-Kerberoast.ps1"

LINUX_LINPEAS_URL="https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh"
LINUX_LINENUM_URL="https://raw.githubusercontent.com/rebootuser/LinEnum/master/LinEnum.sh"
LINUX_EXPLOIT_SUGGESTER_URL="https://raw.githubusercontent.com/mzet-/linux-exploit-suggester/master/linux-exploit-suggester.sh"
LINUX_RAPTORUDF2_URL="https://www.exploit-db.com/raw/1518"
LINUX_PSPY64_URL="https://github.com/DominicBreuker/pspy/releases/latest/download/pspy64"
LINUX_PSPY32_URL="https://github.com/DominicBreuker/pspy/releases/latest/download/pspy32"
LINUX_JOHNTHERIPPER_URL="https://github.com/openwall/john"

WORDLIST_COMMON_URL="https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/common.txt"
WORDLIST_DIRECTORY_MEDIUM_URL="https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/directory-list-2.3-medium.txt"


rm -rf "/opt/windows_tools/" && echo "[-] Deleted windows_tools directory"
rm -rf "/opt/linux_tools/" && echo "[-] Deleted linux_tools directory"
rm -rf "/opt/wordlists/" && echo "[-] Deleted wordlists directory"
rm "/opt/aliases" && echo "[-] Deleted aliases file"

mkdir "/opt/windows_tools/" && echo "[+] Created windows_tools directory"
curl -s -k -L "$WINDOWS_WINPEASANY_URL" -o "/opt/windows_tools/winPEASany.exe" >/dev/null && echo "[*] windows_tools -> winPEASany.exe"
cp $WINDOWS_NC_LOCAL /opt/windows_tools/nc.exe && echo "[*] windows_tools -> nc.exe"
curl -s -k -L "$WINDOWS_ACCESSCHK_OLD_URL" -o "/opt/windows_tools/accesschk.zip" >/dev/null && unzip -q "/opt/windows_tools/accesschk.zip" -d "/opt/windows_tools/" && rm "/opt/windows_tools/Eula.txt" "/opt/windows_tools/accesschk.zip" && echo "[*] windows_tools -> accesschk.exe"
curl -s -k -L "$WINDOWS_PROCDUMP_URL" -o "/opt/windows_tools/procdump.zip" >/dev/null && unzip -q "/opt/windows_tools/procdump.zip" -d "/opt/windows_tools" && rm "/opt/windows_tools/Eula.txt" "/opt/windows_tools/procdump64a.exe" "/opt/windows_tools/procdump.zip" && mv "/opt/windows_tools/procdump.exe" "/opt/windows_tools/procdump32.exe" && mv "/opt/windows_tools/procdump64.exe" "/opt/windows_tools/procdump.exe" && echo "[*] windows_tools -> procdump.exe, procdump32.exe"
mkdir "/opt/windows_tools/psexec/" && curl -s -k -L "$WINDOWS_PSEXEC_URL" -o "/opt/windows_tools/psexec.zip" >/dev/null && unzip -q "/opt/windows_tools/psexec.zip" -d "/opt/windows_tools/psexec" && mv "/opt/windows_tools/psexec/PsExec64.exe" "/opt/windows_tools/psexec.exe" && mv "/opt/windows_tools/psexec/PsExec.exe" "/opt/windows_tools/psexec32.exe" && rm -rf "/opt/windows_tools/psexec/" "/opt/windows_tools/psexec.zip" && echo "[*] windows_tools -> psexec.exe, psexec32.exe" 
curl -s -k -L "$WINDOWS_JUICYPOTATO64_URL" -o "/opt/windows_tools/juicypotato.exe" >/dev/null && echo "[*] windows_tools -> juicypotato.exe"
curl -s -k -L "$WINDOWS_JUICYPOTATO32_URL" -o "/opt/windows_tools/juicypotato32.exe" >/dev/null && echo "[*] windows_tools -> juicypotato32.exe"
curl -s -k -L "$WINDOWS_PRINTSPOOFER64_URL" -o "/opt/windows_tools/printspoofer.exe" >/dev/null && echo "[*] windows_tools -> printspoofer.exe"
curl -s -k -L "$WINDOWS_PRINTSPOOFER32_URL" -o "/opt/windows_tools/printspoofer32.exe" >/dev/null && echo "[*] windows_tools -> printspoofer32.exe"

curl -s -k -L "$WINDOWS_MIMIKATZ_URL" -o "/opt/windows_tools/mimikatz.zip" >/dev/null && unzip -q "/opt/windows_tools/mimikatz.zip" -d "/opt/windows_tools" && cp "/opt/windows_tools/Win32/mimikatz.exe" "/opt/windows_tools/mimikatz32.exe" && cp "/opt/windows_tools/x64/mimikatz.exe" "/opt/windows_tools/mimikatz.exe" && rm -rf "/opt/windows_tools/README.md" "/opt/windows_tools/mimicom.idl" "/opt/windows_tools/kiwi_passwords.yar" "/opt/windows_tools/x64" "/opt/windows_tools/Win32" "/opt/windows_tools/mimikatz.zip" && echo "[*] windows_tools -> mimikatz.exe, mimikatz32.exe"
curl -s -k -L "$WINDOWS_MIMIKATZ_OLD_URL" -o "/opt/windows_tools/mimikatz_old.zip" >/dev/null && unzip -q "/opt/windows_tools/mimikatz_old.zip" -d "/opt/windows_tools" && cp "/opt/windows_tools/Win32/mimikatz.exe" "/opt/windows_tools/mimikatz32_old.exe" && cp "/opt/windows_tools/x64/mimikatz.exe" "/opt/windows_tools/mimikatz_old.exe" && rm -rf "/opt/windows_tools/README.md" "/opt/windows_tools/mimicom.idl" "/opt/windows_tools/kiwi_passwords.yar" "/opt/windows_tools/x64" "/opt/windows_tools/Win32" "/opt/windows_tools/mimikatz_old.zip" && echo "[*] windows_tools -> mimikatz_old.exe, mimikatz32_old.exe"
curl -s -k -L "$WINDOWS_MS16_032_64_URL" -o "/opt/windows_tools/ms16-032.exe" >/dev/null && echo "[*] windows_tools -> ms16-032.exe"
curl -s -k -L "$WINDOWS_MS16_032_32_URL" -o "/opt/windows_tools/ms16-032_32.exe" >/dev/null && echo "[*] windows_tools -> ms16-032_32.exe"
curl -s -k -L "$WINDOWS_NMAP32_URL" -o "/opt/windows_tools/nmap32.exe" >/dev/null && echo "[*] windows_tools -> nmap32.exe"
curl -s -k -L "$WINDOWS_EXPLOIT_SUGGESTER_URL" -o "/opt/windows_tools/windows-exploit-suggester.py" >/dev/null && echo "[*] windows_tools -> windows-exploit-suggester.py"
curl -s -k -L "$WINDOWS_POWERVIEW_URL" -o "/opt/windows_tools/powerview.ps1" >/dev/null && echo "[*] windows_tools -> powerview.ps1"
curl -s -k -L "$WINDOWS_GETSPN_URL" -o "/opt/windows_tools/Get-SPN.ps1" >/dev/null && echo "[*] windows_tools -> Get-SPN.ps1"
git clone --quiet "$WINDOWS_KERBEROAST_URL" "/opt/windows_tools/kerberoast/" >/dev/null && echo "[*] windows_tools -> kerberoast repo"
curl -s -k -L "$WINDOWS_INVOKE_KERBEROAST_URL" -o "/opt/windows_tools/Invoke-Kerberoast.ps1" >/dev/null && echo "[*] windows_tools -> Invoke-Kerberoast.ps1"

mkdir "/opt/linux_tools/" && echo "[+] Created linux_tools directory"
curl -s -k -L "$LINUX_LINPEAS_URL" -o "/opt/linux_tools/linpeas.sh" >/dev/null && echo "[*] linux_tools -> linpeas.sh"
curl -s -k -L "$LINUX_LINENUM_URL" -o "/opt/linux_tools/linenum.sh" >/dev/null && echo "[*] linux_tools -> linenum.sh"
curl -s -k -L "$LINUX_EXPLOIT_SUGGESTER_URL" -o "/opt/linux_tools/linux-exploit-suggester.sh" >/dev/null && echo "[*] linux_tools -> linux-exploit-suggester.sh"
curl -s -k -L "$LINUX_RAPTORUDF2_URL" -o "/opt/linux_tools/raptor_udf2.c" >/dev/null && echo "[*] linux_tools -> raptor_udf2.c"
curl -s -k -L "$LINUX_PSPY64_URL" -o "/opt/linux_tools/pspy" >/dev/null && echo "[*] linux_tools -> pspy"
curl -s -k -L "$LINUX_PSPY32_URL" -o "/opt/linux_tools/pspy32" >/dev/null && echo "[*] linux_tools -> pspy32"
git clone --quiet "$LINUX_JOHNTHERIPPER_URL" "/opt/linux_tools/johntheripper/" >/dev/null && echo "[*] linux_tools -> johntheripper repo"

mkdir "/opt/wordlists/" && echo "[+] Created wordlists directory"
curl -s -k -L "$WORDLIST_COMMON_URL" -o "/opt/wordlists/common.txt" >/dev/null && echo "[*] wordlists -> common.txt"
curl -s -k -L "$WORDLIST_DIRECTORY_MEDIUM_URL" -o "/opt/wordlists/directory-list-2.3-medium.txt" >/dev/null && echo "[*] wordlists -> directory-list-2.3-medium.txt"
cat /opt/wordlists/* | sort | uniq > "/tmp/directories.txt" && rm /opt/wordlists/* && mv "/tmp/directories.txt" "/opt/wordlists/directories.txt" && echo "[*] wordlists :: merged all wordlists into directories.txt"


touch "/opt/aliases" && echo "[+] Created aliases file"
echo "alias portscan='sudo nmap -A -T4 -p-'" >> /opt/aliases && echo "[*] aliases -> portscan"
echo "alias portscan_quick='sudo masscan -p20,21-23,25,53,80,110,111,135,139,143,443,445,993,995,1723,3306,3389,5900,8080'" >> /opt/aliases && echo "[*] aliases -> portscan_quick"
echo "alias portscan_udp='sudo nmap -sU -A --top-ports=20 --version-all'" >> /opt/aliases && echo "[*] aliases -> portscan_udp"
echo "alias vulnscan='sudo nmap -sV --script vuln'" >> /opt/aliases && echo "[*] aliases -> vulnscan"
echo "alias dirscan='gobuster dir -k -e -w /opt/wordlists/directories.txt -t 50 -u'" >> /opt/aliases && echo "[*] aliases -> dirscan"
